# Generated by Django 4.0.3 on 2022-05-02 10:12

from django.db import migrations, models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='schema_name',
            field=models.CharField(max_length=63, validators=[tenant_schemas.postgresql_backend.base._check_schema_name]),
        ),
    ]
