# Generated by Django 4.0.3 on 2022-05-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='domain_url',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
