# Generated by Django 4.0.3 on 2022-03-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    default='Uncategorized', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='transac',
            old_name='name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='transac',
            name='category',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.category'),
            preserve_default=False,
        ),
    ]
