# Generated by Django 4.0.3 on 2022-03-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_category_rename_name_transac_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(
                default='Uncategorized', max_length=100, unique=True),
        ),
    ]
