# Generated by Django 4.0.3 on 2022-03-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transac',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transac',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
